stages:
    - check
    - build
    - test
eslint:
    stage: check
    script:
        - npm i
        - npm run lint
build_container:
    stage: build
    needs: 
        - eslint
    before_script:
        - docker info
    script:
        - docker build -t ryois/blob-image-hosting-web-ui .